TocNotFoundNoError: TOC no longer generates an error message when there is no TOC to construct (it's just empty instead)
git-svn-id: http://develop.twiki.org/svn/twiki/branches/DEVELOP@3536 a00a5322-12db-0310-a70b-8735589c885e