SearchCantUseStringError: misread old code when converting and introduced an error. Now fixed.
git-svn-id: http://develop.twiki.org/svn/twiki/branches/DEVELOP@3489 a00a5322-12db-0310-a70b-8735589c885e